"""fix_skill_enums_case

Revision ID: fb8df5a87f9a
Revises: 001_initial_migration
Create Date: 2026-06-02 10:41:50.275549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fb8df5a87f9a'
down_revision: Union[str, None] = '001_initial_migration'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('certifications', 'is_verified',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=True)
    op.alter_column('certifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('club_members', 'role',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    op.alter_column('club_members', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('clubs', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('event_registrations', 'status',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    op.alter_column('events', 'capacity',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('events', 'is_published',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('events', 'is_cancelled',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('mentor_messages', 'is_read',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('mentoring_sessions', 'duration_min',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('mentoring_sessions', 'status',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    op.alter_column('mentorships', 'match_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('mentorships', 'status',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    op.alter_column('project_applications', 'match_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('project_applications', 'status',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    op.alter_column('project_members', 'role',
               existing_type=sa.VARCHAR(length=100),
               server_default=None,
               existing_nullable=False)
    op.alter_column('project_members', 'status',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    op.alter_column('projects', 'status',
               existing_type=postgresql.ENUM('brouillon', 'OPEN', 'ouvert', 'en cours', 'terminé', 'annulé', name='projectstatus'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('projects', 'max_members',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('projects', 'required_hours_per_week',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('user_skills', 'is_validated',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('STUDENT', 'student', 'mentor', 'club_admin', 'admin', name='userrole'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'is_available',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'hours_per_week',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'hours_per_week',
               existing_type=sa.INTEGER(),
               server_default=sa.text('10'),
               existing_nullable=False)
    op.alter_column('users', 'is_available',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('STUDENT', 'student', 'mentor', 'club_admin', 'admin', name='userrole'),
               server_default=sa.text("'student'::userrole"),
               existing_nullable=False)
    op.alter_column('user_skills', 'is_validated',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('projects', 'required_hours_per_week',
               existing_type=sa.INTEGER(),
               server_default=sa.text('8'),
               existing_nullable=False)
    op.alter_column('projects', 'max_members',
               existing_type=sa.INTEGER(),
               server_default=sa.text('5'),
               existing_nullable=False)
    op.alter_column('projects', 'status',
               existing_type=postgresql.ENUM('brouillon', 'OPEN', 'ouvert', 'en cours', 'terminé', 'annulé', name='projectstatus'),
               server_default=sa.text("'ouvert'::projectstatus"),
               existing_nullable=False)
    op.alter_column('project_members', 'status',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'accepted'::character varying"),
               existing_nullable=False)
    op.alter_column('project_members', 'role',
               existing_type=sa.VARCHAR(length=100),
               server_default=sa.text("'membre'::character varying"),
               existing_nullable=False)
    op.alter_column('project_applications', 'status',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'pending'::character varying"),
               existing_nullable=False)
    op.alter_column('project_applications', 'match_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'0'::double precision"),
               existing_nullable=False)
    op.alter_column('mentorships', 'status',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'active'::character varying"),
               existing_nullable=False)
    op.alter_column('mentorships', 'match_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'0'::double precision"),
               existing_nullable=False)
    op.alter_column('mentoring_sessions', 'status',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'scheduled'::character varying"),
               existing_nullable=False)
    op.alter_column('mentoring_sessions', 'duration_min',
               existing_type=sa.INTEGER(),
               server_default=sa.text('60'),
               existing_nullable=False)
    op.alter_column('mentor_messages', 'is_read',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('events', 'is_cancelled',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('events', 'is_published',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('events', 'capacity',
               existing_type=sa.INTEGER(),
               server_default=sa.text('50'),
               existing_nullable=False)
    op.alter_column('event_registrations', 'status',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'confirmed'::character varying"),
               existing_nullable=False)
    op.alter_column('clubs', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('club_members', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('club_members', 'role',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'membre'::character varying"),
               existing_nullable=False)
    op.alter_column('certifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
    op.alter_column('certifications', 'is_verified',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               nullable=False)
    # ### end Alembic commands ###